name: Static code analysis

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*-GHTEST"
      - "*-GHTESTSTATIC"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-code-analysis:
    name: Static Code Analysis
    uses: ministryofjustice/nvvs-devops-github-actions/.github/workflows/static-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
    with:
      TRIVY_IGNORES: '.trivyignore.yaml'
      REPO_TYPE: tf
      